version: '3.8'

services:
  db:
    image: postgres:17.4
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - ./api:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    depends_on:
      - api
    volumes:
      - ./frontend:/app

volumes:
  db_data:
    name: db_data
