services:
  db:
    image: postgres:17.4
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - ./api:/app
      # preserve dependencies installed in image
      - api_node_modules:/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      # preserve dependencies installed in image
      - frontend_node_modules:/app/node_modules

volumes:
  db_data:
    name: db_data
  # named volumes to hold node_modules for each service
  api_node_modules:
  frontend_node_modules:
